version: '3.8'
services:
  database:
    image: library/postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: dbmain
      POSTGRES DB: main
    ports: [ 5432 ]

  redis:
    image: library/redis:6-alpine
    ports: [6379]